# Generated by Django 4.2.3 on 2023-07-19 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0002_gasto_descripcion"),
    ]

    operations = [
        migrations.RemoveField(model_name="gasto", name="descripcion",),
    ]
