# Generated by Django 4.2.3 on 2023-07-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0003_remove_gasto_descripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="gasto",
            name="comprobante",
            field=models.ImageField(default=0, upload_to="static/media"),
            preserve_default=False,
        ),
    ]
