# Generated by Django 4.2.3 on 2023-07-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0004_gasto_comprobante"),
    ]

    operations = [
        migrations.RemoveField(model_name="gasto", name="fecha",),
        migrations.AlterField(
            model_name="gasto",
            name="comprobante",
            field=models.ImageField(upload_to="comprobantes"),
        ),
    ]
