# Generated by Django 4.2.3 on 2023-07-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0005_remove_gasto_fecha_alter_gasto_comprobante"),
    ]

    operations = [
        migrations.AddField(
            model_name="gasto",
            name="mes",
            field=models.CharField(default="J", max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gasto",
            name="cuenta",
            field=models.CharField(
                choices=[
                    ("V", "Vero"),
                    ("M", "Moni"),
                    ("G", "Gerardo"),
                    ("W", "Walter"),
                    ("J", "Jubilacion"),
                ],
                default="J",
                max_length=1,
            ),
        ),
    ]
