# Generated by Django 4.2.3 on 2023-07-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0006_gasto_mes_alter_gasto_cuenta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gasto",
            name="cuenta",
            field=models.CharField(
                choices=[
                    ("V", "Vero"),
                    ("M", "Moni"),
                    ("G", "Gerardo"),
                    ("W", "Walter"),
                    ("J", "Jubilacion"),
                ],
                default="Jubilacion",
                max_length=1,
            ),
        ),
    ]
