# Generated by Django 4.2.3 on 2023-07-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0009_alter_gasto_cuenta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gasto",
            name="mes",
            field=models.CharField(
                choices=[
                    ("E", "Enero"),
                    ("F", "Febrero"),
                    ("M", "Marzo"),
                    ("A", "Abril"),
                    ("M", "Mayo"),
                    ("J", "Junio"),
                    ("J", "Julio"),
                    ("A", "Agosto"),
                    ("S", "Septiembre"),
                    ("O", "Octubre"),
                    ("N", "Noviembre"),
                    ("D", "Diciembre"),
                ],
                max_length=1,
            ),
        ),
    ]
