# Generated by Django 4.1.3 on 2023-07-21 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0010_alter_gasto_mes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jubilacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.IntegerField()),
            ],
        ),
    ]
