# Generated by Django 4.1.3 on 2023-07-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0012_alter_gasto_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gasto",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("M", "Medicamentos"),
                    ("S", "Supermercado"),
                    ("E", "Empleados/as"),
                    ("V", "Servicios"),
                    ("C", "Comprobantes"),
                    ("O", "Otros"),
                ],
                max_length=1,
            ),
        ),
    ]
