# Generated by Django 4.1.3 on 2023-07-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0013_alter_gasto_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gasto",
            name="mes",
            field=models.CharField(
                choices=[
                    ("E", "Enero"),
                    ("F", "Febrero"),
                    ("M", "Marzo"),
                    ("A", "Abril"),
                    ("m", "Mayo"),
                    ("J", "Junio"),
                    ("j", "Julio"),
                    ("a", "Agosto"),
                    ("S", "Septiembre"),
                    ("O", "Octubre"),
                    ("N", "Noviembre"),
                    ("D", "Diciembre"),
                ],
                max_length=1,
            ),
        ),
    ]
